### ISSUE TITLE
Extension does not honor table prefixes

### ISSUE THREAD

**Issue by PrplHaz4** [SleepWalker/hoauth#6]
table name is hardcoded, and should be

```
    /**
     * @return string the associated database table name
     */
    public function tableName()
    {
        return '{{user_oauth}}';
    }
```

but this will break the table renaming hack, which should exist as a migration, not in the model script (IMO).

I have a migration for the table creation, but not one that will update it between the two existing versions (if you would like it).

**Comment by PrplHaz4** [comment]
@SleepWalker please let me know if you would find the migration useful

Thx for the extension!

**Comment by SleepWalker** [comment]
@PrplHaz4 Yes, I think it will be useful. I had not used migration before, thats why haven't implement it. When you have something for it done, it will be good for beginning.

But when it is working only in command line, probably I will continue to write hardcoded in model updates. Because this updates will be not too often (I hope that it will be only one more. I think, that it is better to save copy of profile object in database. It will be useful for widget that will display all networks, that user had associated with his account.) and it will be comfortable for user, when everything will be working without any command lines.

Or when you need to use migration, I can make both variants of updates.

**Comment by SleepWalker** [comment]
@PrplHaz4, now hoauth works also with both prefixed and not prefixed table names configs.

P.S. the table name will be automatically changed, if in your config enabled prefix for table name.

**Comment by PrplHaz4** [comment]
@SleepWalker :+1:  cool...will post back when I've had a chance to test it out
